"""Fix optional columns in Productlink, Feedback tables

Revision ID: d1012bc826e1
Revises: 42489c82c311
Create Date: 2024-07-09 11:21:23.561192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1012bc826e1'
down_revision: Union[str, None] = '42489c82c311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('productlink', 'link_short_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productlink', 'link_short_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('feedback', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
