"""Create tables BoughtInProduct, Unit, ProductLink

Revision ID: feb22d2509c2
Revises: 38fe6e7e0aaf
Create Date: 2024-06-19 12:20:49.002203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb22d2509c2'
down_revision: Union[str, None] = '38fe6e7e0aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boughtinproduct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.SmallInteger(), nullable=True),
    sa.Column('product_type', sa.String(length=128), nullable=True),
    sa.Column('comment', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bought_in_product_id', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('link_short_name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['bought_in_product_id'], ['boughtinproduct.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productlink')
    op.drop_table('boughtinproduct')
    op.drop_table('unit')
    # ### end Alembic commands ###
