"""Remove some indexes from Question model

Revision ID: b0daaff34327
Revises: feb22d2509c2
Create Date: 2024-06-21 06:37:52.185243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0daaff34327'
down_revision: Union[str, None] = 'feb22d2509c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_is_condemned', table_name='question')
    op.drop_index('ix_question_is_published', table_name='question')
    op.drop_index('ix_question_question_type', table_name='question')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_question_question_type', 'question', ['question_type'], unique=False)
    op.create_index('ix_question_is_published', 'question', ['is_published'], unique=False)
    op.create_index('ix_question_is_condemned', 'question', ['is_condemned'], unique=False)
    # ### end Alembic commands ###
