name: brain_system_prod_fastapi

volumes:
  pg_data:
  static:
  es_data:


services:

  db:
    image: arm64v8/postgres:16
    restart: always
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  
  redis:
    image: arm64v8/redis:7
    restart: always
    env_file: ../.env
    command:
      - /bin/sh
      - -c
      - redis-server --port "$${REDIS_PORT}" --requirepass "$${REDIS_PASSWORD}"
  
  es:
    image: arm64v8/elasticsearch:8.14.2
    restart: always
    env_file: ../.env
    volumes:
      - es_data:/usr/share/elasticsearch/data/

  tg_bot:
    build:
      context: ../telegram_bot/
      dockerfile: telegram_bot_ARM64.Dockerfile
    env_file: ../.env
    restart: always
    depends_on:
      - db
  
  backend_api:
    build:
      context: ../
      dockerfile: backend_api_ARM64.Dockerfile
    env_file: ../.env
    depends_on:
      - db
      - redis
      - es
  
  backend_pages:
    build:
      context: ../
      dockerfile: backend_pages_ARM64.Dockerfile
    env_file: ../.env
    volumes:
      - static:/app/app/static/
    depends_on:
      - db
      - redis
      - es
  
  celery:
    build:
      context: ../
      dockerfile: backend_celery_ARM64.Dockerfile
    env_file: ../.env
    depends_on:
      - db
      - backend_api
      - redis
  
  nginx:
    build:
      context: ./
      dockerfile: nginx_ARM64.Dockerfile
    ports:
      - "8000:80"
      - "9000:90"
    volumes:
      - static:/staticfiles/
    depends_on:
      - db
      - redis
      - backend_api
      - backend_pages
